### ISSUE TITLE
http://downloads.blackberry.com/upr/developers/update/bbndk/unittesting/ is not a valid update site

### ISSUE THREAD

**Issue by dmdrummond** [blackberry/MomenticsUnitTestingPlugin#1]
http://downloads.blackberry.com/upr/developers/update/bbndk/unittesting/ is not a valid update site.  When accessing it through Momentics, it just sits there not doing anything.  When I visit it in a browser, I am informed:

File not found."

**Comment by tallenbb** [comment]
I added the following URL as an update site in Momentics and it worked as expected: http://downloads.blackberry.com/upr/developers/update/bbndk/unittesting/

Depending on your connection it may take a little bit to collect all of the information from the required update sites before displaying anything.

You will not be able to browse to the URL in a browser -- it is not a website.

Please try again and if it is still an issue re-open the ticket.

**Comment by dmdrummond** [comment]
It may have been a connection issue.  After leaving for a long time, it populated the listbox with updates.
